<?php echo AUTOGENERATED_CONFIGS; ?>

<?php /** @var Template_VariableAccessor $VAR */ ?>
<?php if (!$VAR->domain->active): ?>

# Domain is disabled or suspended

<?php return ?>
<?php endif ?>

<?php foreach ($VAR->domain->forwarding->ipAddresses as $ipAddress): ?>
<?php     if ($ipAddress->defaultDomainId != $VAR->domain->id): ?>
<?php         if ($VAR->domain->hasStandardForwarding || $VAR->domain->hasFrameForwarding): ?>

<?php             echo $VAR->includeTemplate('domain/nginxForwarding.php', array(
                      'ipAddress' => $ipAddress,
                      'frontendPort' => $VAR->server->nginx->httpPort,
                      'backendPort' => $VAR->server->webserver->httpPort,
                      'default' => false,
)) ?>

<?php         endif ?>

<?php     endif ?>
<?php endforeach ?>
