<?php echo AUTOGENERATED_CONFIGS; ?>

<?php /** @var Template_VariableAccessor $VAR */ ?>
<?php /** @var Template_Variable_IpAddress $ipAddress */ ?>

include "<?php echo $VAR->server->nginx->httpConfDir ?>/plesk.conf.d/ip_default/*.conf";

<?php echo $VAR->includeTemplate('server/nginxVhosts.php', array(
    'ssl' => false,
    'frontendPort' => $VAR->server->nginx->httpPort,
    'backendPort' => $VAR->server->webserver->httpPort,
)) ?>

<?php echo $VAR->includeTemplate('server/nginxVhosts.php', array(
    'ssl' => true,
    'frontendPort' => $VAR->server->nginx->httpsPort,
    'backendPort' => $VAR->server->webserver->httpsPort,
)) ?>

<?php /* Next block used for watchdog */ ?>
<?php if (!$VAR->server->ipAddresses->hasIpV4Address): ?>
server {
    listen 127.0.0.1 default_server;
    return 200;
}
<?php endif ?>